"""
Architecture implementation for Attention-based Multiple Instance Learning (MIL)
coupled with Nucleotide Transformer v2/v3 backbones for bacterial phenotype prediction.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModel


class FocalLoss(nn.Module):
    """
    Focal Loss for binary classification with raw logits.
    Down-weights easy examples to focus gradient updates on hard examples (e.g. resistant class R).

    Parameters
    ----------
    alpha : float, default=0.55
        Weight factor for class 1 (Resistant). alpha > 0.5 favors sensitivity/recall for class R.
    gamma : float, default=2.0
        Focusing parameter modulating the penalization for easy examples.
    """
    def __init__(self, alpha: float = 0.55, gamma: float = 2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
        ce = F.cross_entropy(logits, targets, reduction="none")
        pt = torch.exp(-ce)
        alpha_t = torch.where(
            targets == 1,
            torch.tensor(self.alpha, device=logits.device),
            torch.tensor(1.0 - self.alpha, device=logits.device),
        )
        focal = alpha_t * (1.0 - pt) ** self.gamma * ce
        return focal.mean()


class NTv3MultiHeadMIL(nn.Module):
    """
    Multiple Instance Learning (MIL) model using multi-head attention pooling
    over gene embeddings generated by a Nucleotide Transformer foundation model.

    Workflow:
      1. NTv3 encoder extracts the [CLS] embedding (768-dim) for each resistance gene.
      2. LayerNorm normalizes embedding scale across bags.
      3. Dropout regularizes gene embeddings.
      4. Multi-head attention (num_heads parallel attention networks) learns distinct
         biological mechanisms (e.g., carbapenemases, porin loss, efflux pumps).
      5. Context vectors are concatenated, projected back to 768-dim, and classified.

    Parameters
    ----------
    model_name : str, default="InstaDeepAI/NTV3_100M_post"
        HuggingFace model identifier for the pretrained Nucleotide Transformer.
    hidden_dim : int, default=128
        Dimension of the attention mechanism hidden layer.
    num_heads : int, default=4
        Number of parallel attention heads.
    embed_dropout : float, default=0.15
        Dropout probability applied to gene embeddings.
    """
    def __init__(
        self,
        model_name: str = "InstaDeepAI/NTV3_100M_post",
        hidden_dim: int = 128,
        num_heads: int = 4,
        embed_dropout: float = 0.15,
    ):
        super().__init__()
        self.ntv3 = AutoModel.from_pretrained(model_name, trust_remote_code=True)
        self.layer_norm = nn.LayerNorm(768)
        self.embed_dropout = nn.Dropout(embed_dropout)
        self.attention_heads = nn.ModuleList([
            nn.Sequential(
                nn.Linear(768, hidden_dim),
                nn.Tanh(),
                nn.Dropout(0.1),
                nn.Linear(hidden_dim, 1),
            )
            for _ in range(num_heads)
        ])
        self.projection = nn.Linear(768 * num_heads, 768)
        self.proj_norm = nn.LayerNorm(768)
        self.classifier = nn.Linear(768, 2)
        self.dropout = nn.Dropout(0.1)

    def encode_genes(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        species_ids: torch.Tensor,
    ) -> torch.Tensor:
        """
        Runs forward pass of the transformer encoder and extracts LayerNorm + Dropout [CLS] embeddings.
        """
        out = self.ntv3(
            input_ids=input_ids,
            attention_mask=attention_mask,
            species_ids=species_ids,
            output_hidden_states=True,
        )
        emb = out.hidden_states[-1][:, 0, :]
        emb = self.layer_norm(emb)
        emb = self.embed_dropout(emb)
        return emb

    def classify(self, gene_embeddings: torch.Tensor):
        """
        Pools gene embeddings using multi-head attention and produces isolate-level logits.

        Parameters
        ----------
        gene_embeddings : torch.Tensor of shape [N_genes, 768]

        Returns
        -------
        logits : torch.Tensor of shape [1, 2]
        attn_weights_per_head : list of torch.Tensor
            Attention weight tensors [N_genes, 1] for each head.
        """
        head_contexts, attn_weights_per_head = [], []
        for attn_net in self.attention_heads:
            scores = attn_net(gene_embeddings)
            weights = torch.softmax(scores, dim=0)
            context = (weights * gene_embeddings).sum(dim=0)
            head_contexts.append(context)
            attn_weights_per_head.append(weights)

        multi_context = torch.cat(head_contexts, dim=0)
        genome_emb = self.proj_norm(self.projection(multi_context))
        logits = self.classifier(self.dropout(genome_emb.unsqueeze(0)))
        return logits, attn_weights_per_head
